version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000" # Port pour PHP-FPM
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app-crud
      DB_USERNAME: root
      DB_PASSWORD: yourpassword
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: laravel_webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: app-crud
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
